"core":
  - src/**/*

"tests":
  - tests/**/*

"[documentation]":
  - docs/**/*
  - "*.md"

"github":
  - .github/**/*

"ci":
  - ".github/workflows/**/*"
  - ".github/actions/**/*"

"dependencies":
  - package.json
  - pnpm-lock.yaml

"tools":
  - eslint.config.mjs
  - prettier.config.mjs

"bug":
  - head-branch: ["fix/", "bug/", "bugfix/", "hotfix/"]

"feature":
  - head-branch: ["feat/", "feature/"]
