core:
  - changed-files:
      - any-glob-to-any-file: ["src/**/*"]

tests:
  - changed-files:
      - any-glob-to-any-file: ["tests/**/*"]

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "*.md"

github:
  - changed-files:
      - any-glob-to-any-file: [".github/**/*"]

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".github/actions/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"

tools:
  - changed-files:
      - any-glob-to-any-file:
          - "eslint.config.mjs"
          - "prettier.config.mjs"

bug:
  - head-branch: ["^fix/", "^bug/", "^bugfix/", "^hotfix/"]

feature:
  - head-branch: ["^feat/", "^feature/"]
